name: Version Bump

on:
  pull_request:
    branches:
      - main

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Bump Version
        run: npm version patch --no-git-tag-version

      - name: Commit Version Change
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add .
          git commit -m "Bump minor version [skip ci]"

      - name: Pull Latest Changes
        run: git pull origin main --rebase

      - name: Push Changes
        run: git push origin HEAD:main
